# Generated by Django 5.0.4 on 2026-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название отправки')),
                ('sender', models.CharField(max_length=150, verbose_name='Отправитель')),
                ('receiver', models.CharField(max_length=150, verbose_name='Получатель')),
                ('route', models.CharField(blank=True, max_length=200, verbose_name='Маршрут')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('В пути', 'В пути'), ('На складе', 'На складе'), ('Доставлен', 'Доставлен'), ('Отменён', 'Отменён')], default='Создан', max_length=20, verbose_name='Статус')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вес (кг)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-created_at'],
            },
        ),
    ]
