# Generated by Django 5.0.4 on 2026-04-11 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_destination_lat_shipment_destination_lng_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отправка', 'verbose_name_plural': 'Отправки'},
        ),
        migrations.AlterModelOptions(
            name='shipmentlocation',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AddField(
            model_name='shipment',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое прибытие'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Задержка в минутах'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delay_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина задержки'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемое прибытие'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='fragile_level',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='low', max_length=20, verbose_name='Уровень хрупкости'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_delayed',
            field=models.BooleanField(default=False, verbose_name='Есть задержка'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_fragile',
            field=models.BooleanField(default=False, verbose_name='Хрупкий груз'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Прогресс маршрута'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('docs', 'Документы'), ('ready', 'Готов к отправке'), ('in_transit', 'В пути'), ('delayed', 'Задерживается'), ('border', 'На границе'), ('done', 'Доставлен'), ('cancelled', 'Отменён')], default='created', max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Водитель'), ('company', 'Компания')], default='company', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
