# Generated by Django 5.0.4 on 2026-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipmentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город назначения'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город отправления'),
        ),
    ]
