# Generated by Django 5.0.4 on 2026-04-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('docs', 'Документы'), ('in_transit', 'В пути'), ('border', 'На границе'), ('done', 'Доставлен')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ShipmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('signed_by_sender', models.BooleanField(default=False)),
                ('signed_by_receiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='shipments.shipment')),
            ],
        ),
    ]
