# Generated by Django 5.0.4 on 2026-04-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_options_remove_shipment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cmr', 'CMR'), ('invoice', 'Инвойс'), ('packing_list', 'Упаковочный лист'), ('certificate', 'Сертификат'), ('customs', 'Таможенный документ'), ('passport', 'Паспорт водителя'), ('vehicle_passport', 'Техпаспорт'), ('insurance', 'Страховка'), ('other', 'Другое')], default='other', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='shipment_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipments.shipment')),
            ],
        ),
    ]
