# Generated by Django 5.0.4 on 2026-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_destination_city_shipment_origin_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
